function generateTestCases() {
    const testCases = [
        { input: { s: "egg", t: "add" }, output: true },
        { input: { s: "foo", t: "bar" }, output: false },
        { input: { s: "paper", t: "title" }, output: true },
        { input: { s: "ab", t: "aa" }, output: false },
        { input: { s: "ab", t: "ca" }, output: true },
        { input: { s: "aa", t: "bb" }, output: true },
        { input: { s: "abba", t: "cddc" }, output: true },
        { input: { s: "abba", t: "abba" }, output: true },
        { input: { s: "abba", t: "aaaa" }, output: false },
        { input: { s: "hello", t: "world" }, output: false },
        { input: { s: "title", t: "paper" }, output: true },
        { input: { s: "badc", t: "baba" }, output: false },
        { input: { s: "13", t: "42" }, output: true },
        { input: { s: "131", t: "424" }, output: false },
        { input: { s: "a", t: "b" }, output: true },
        { input: { s: "abc", t: "def" }, output: true },
        { input: { s: "aab", t: "xyz" }, output: false },
        { input: { s: "racecar", t: "abcdbcb" }, output: true },
        { input: { s: "turtle", t: "pigeon" }, output: false },
        { input: { s: "paper", t: "title" }, output: true },
        { input: { s: "foo", t: "bee" }, output: true },
        { input: { s: "bar", t: "foo" }, output: false },
        { input: { s: "abc", t: "abc" }, output: true },
        { input: { s: "abcdefg", t: "1234567" }, output: true },
        { input: { s: "abcdefg", t: "1234561" }, output: false },
        { input: { s: "aba", t: "bab" }, output: true },
        { input: { s: "aba", t: "baa" }, output: false },
        { input: { s: "ab", t: "ab" }, output: true },
        { input: { s: "ab", t: "ba" }, output: true },
        { input: { s: "aabbcc", t: "aabbcc" }, output: true },
        { input: { s: "aabbcc", t: "abcabc" }, output: false },
        { input: { s: "abcabc", t: "defdef" }, output: true },
        { input: { s: "abcabc", t: "defdeg" }, output: false },
        { input: { s: "!@#", t: "123" }, output: true },
        { input: { s: "!@#$", t: "1234" }, output: true },
        { input: { s: "!@#$", t: "1233" }, output: false },
        { input: { s: "  ", t: "ab" }, output: true },
        { input: { s: "a a", t: "b c" }, output: true },
        { input: { s: "a a", t: "b b" }, output: true },
        { input: { s: "a a", t: "a b" }, output: false },
        { input: { s: "abcdefghijklmnopqrstuvwxyz", t: "ABCDEFGHIJKLMNOPQRSTUVWXYZ" }, output: true },
        { input: { s: "abcdefghijklmnopqrstuvwxyz", t: "ABCDEFGHIJKLMNOPQRSTUVWXYA" }, output: false },
        { input: { s: "aaabbbccc", t: "111222333" }, output: true },
        { input: { s: "aaabbbccc", t: "111222334" }, output: false },
        { input: { s: "aaaaaaaaa", t: "bbbbbbbbb" }, output: true },
        { input: { s: "aaaaaaaaa", t: "bbbbbbbba" }, output: false },
        { input: { s: "a".repeat(50000), t: "b".repeat(50000) }, output: true },
        { input: { s: "a".repeat(49999) + "b", t: "c".repeat(49999) + "d" }, output: true },
        { input: { s: "a".repeat(49999) + "b", t: "c".repeat(50000) }, output: false },
        { input: { s: "abcdefg".repeat(7143), t: "1234567".repeat(7143) }, output: true }
    ];

    return testCases;
}

module.exports = generateTestCases;